<?php
$films = [
    [
        'id' => '0',
        'titel' => 'Inception',
        'beschrijving' => 'Een dief die dromen steelt krijgt een laatste kans op verlossing. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk.De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk.',
        'tijd' => '19:30',
        'afbeelding' => 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg',
        'genre' => 'Actie',
        'filmlengte' => '248 min',
        'land' => 'USA',
        'lmdb score' => '8.8/10',
        'regisseur' => 'Christopher Nolan',
        'acteurs' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
        'video' => 'https://www.youtube.com/embed/8hP9D6kZseM',
        'rating' => 4,
        'icon' => '⭐',
        'release-date' => '16-07-2010',
    ],
    [
        'id' => '1',
        'titel' => 'The Lion King',
        'beschrijving' => 'Het verhaal van Simba, de leeuwenkoning. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk.De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk.De Avengers nemen het op tegen Thanos in een episch slotstuk.De Avengers nemen het op tegen Thanos in een episch slotstuk. ',
        'tijd' => '17:00',
        'afbeelding' => 'https://play-lh.googleusercontent.com/E4YJiRnNiYlM-PbjVrE2Zdr2d73SWbBTzarMIurgNNdr6c_Bh9IX05-ba6vdNR822EyG',
        'genre' => 'Actie',
        'filmlengte' => '148 min',
        'land' => 'USA',
        'lmdb score' => '8.8/10',
        'regisseur' => 'Christopher Nolan',
        'acteurs' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
        'video' => 'https://www.youtube.com/embed/8hP9D6kZseM',
        'rating' => 5,
        'icon' => '⭐',
        'release-date' => '19-07-2024',
    ],
    [
        'id' => '2',
        'titel' => 'Avengers: Endgame',
        'beschrijving' => 'De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk. De Avengers nemen het op tegen Thanos in een episch slotstuk.',
        'tijd' => '21:00',
        'afbeelding' => 'https://m.media-amazon.com/images/I/81ExhpBEbHL._AC_SY679_.jpg',
        'genre' => 'Actie',
        'filmlengte' => '148 min',
        'land' => 'USA',
        'lmdb score' => '8.8/10',
        'regisseur' => 'Christopher Nolan',
        'acteurs' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
        'video' => 'https://www.youtube.com/embed/8hP9D6kZseM',
        'rating' => 3,
        'icon' => '⭐',
        'release-date' => '26-04-2019',
    ],
];
?>